export const GET_USERS = "GET_USERS";
export const GET_BASIC = "GET_BASIC";
export const GET_USER_ADDRESS = "GET_USER_ADDRESS";
export const GET_UESR_SKILL = "GET_UESR_SKILL";
export const GET_USER_LOCATION = "GET_USER_LOCATION";

export const SELECTED_USER = "SELECTED_USER";
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_BASIC = "UPDATE_BASIC";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
export const UPDATE_UESR_SKILL = "UPDATE_UESR_SKILL";
export const UPDATE_USER_LOCATION = "UPDATE_USER_LOCATION";
export const CLEAR_OLD_DATA = "CLEAR_OLD_DATA";
